x-common-settings: &common-settings
  build: .
  restart: always
  depends_on:
    selenium:
      condition: service_healthy
  volumes:
    - .:/app

services:
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    shm_size: 2g
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://localhost:4444/status | grep '\"ready\": true'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  morda_bot:
    <<: *common-settings
    container_name: morda_bot
    env_file:
      - ./envs/morda.env

  erevan_bot:
    <<: *common-settings
    container_name: erevan_bot
    env_file:
      - ./envs/erevan.env

  tbigirls_bot:
    <<: *common-settings
    container_name: tbigirls_bot
    env_file:
      - ./envs/tbigirls.env
