x-common-settings: &common-settings
  build: .
  restart: always
  volumes:
    - .:/app

services:

  morda_bot:
    <<: *common-settings
    container_name: morda_bot
    env_file:
      - ./envs/morda.env
    # ports:
    #   - "5900:5900" 
  erevan_bot:
    <<: *common-settings
    container_name: erevan_bot
    env_file:
      - ./envs/erevan.env
    # ports:
    #   - "5901:5900"  
  tbigirls_bot:
    <<: *common-settings
    container_name: tbigirls_bot
    env_file:
      - ./envs/tbigirls.env
    # ports:
    #   - "5902:5900"  
