version: "3.4"

x-common-settings: &common-settings
  build: .
  restart: always
  volumes:
    - .:/usr/src/app
  depends_on:
    - selenium-chrome
  networks:
    - custom_network

services:
  selenium-chrome:
    image: selenium/standalone-chrome
    shm_size: 2g
    restart: always
    networks:
      custom_network:
        ipv4_address: 172.0.0.2
    ports:
      - "4444:4444"

  tbilisi_stats_gen:
    <<: *common-settings
    container_name: tbilisi_stats_gen
    command: sh -c "python main.py && sleep 3600"
    env_file:
      - ./envs/tbilisi.env

  tbilisi_bot:
    <<: *common-settings
    container_name: tbilisi_bot
    command: python tg.py
    env_file:
      - ./envs/tbilisi.env

  erevan_stats_gen:
    <<: *common-settings
    container_name: erevan_stats_gen
    command: sh -c "python main.py && sleep 3600"
    env_file:
      - ./envs/erevan.env

  erevan_bot:
    <<: *common-settings
    container_name: erevan_bot
    command: python tg.py
    env_file:
      - ./envs/erevan.env

networks:
  custom_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/24
